### PR TITLE
add syntax_check test

### PR DESCRIPTION
**Pull request by rszyszka**
Please verify if tests is OK

### CODE REVIEW

**Comment by NightWalker23** [comment]
Ok.

**Review by Wasilonek — APPROVED** [review]

**Review by konradtab — APPROVED** [review]
all OK

**Review by NightWalker23 — APPROVED** [review]
Nice :)

**Review by NightWalker23 — APPROVED** [review]
Seems fine.

**Review by Wasilonek — APPROVED** [review]

**Comment by rszyszka** [comment]
NICE!

**Pull request merged**
